LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := sqlite3
LOCAL_SRC_FILES := ./sqlite3.c
LOCAL_CFLAGS := -O3 -std=c99 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_DISABLE_LFS
include $(BUILD_SHARED_LIBRARY)
