apply plugin: 'com.android.application'

android {
	namespace "com.happygoatstudios.bt"
	compileSdk 35

	signingConfigs {
		release {
			storeFile file("../BTLib/key/bt_privatekey.keystore")
			storePassword System.getenv("BT_RELEASE_PASS")
			keyAlias "btkey"
			keyPassword System.getenv("BT_RELEASE_PASS")
		}
	}

	defaultConfig {
		minSdk 31
		targetSdk 35
		versionCode 224
		versionName "2.2"
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}

	buildTypes {
		release {
			minifyEnabled true
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
			signingConfig signingConfigs.release
		}
		debug {
			debuggable true
		}
	}

	lint {
		warningsAsErrors false
		abortOnError false
		xmlReport true
		htmlReport true
		baseline file("lint-baseline.xml")
	}

	sourceSets {
		main {
			manifest.srcFile 'AndroidManifest.xml'
			java.srcDirs = ['src']
			resources.srcDirs = ['src']
			aidl.srcDirs = ['src']
			res.srcDirs = ['res']
			assets.srcDirs = ['assets']
		}
	}
}

dependencies {
	implementation project(":BTLib")
}
