plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
    alias(libs.plugins.detekt)
}

detekt {
	config.setFrom(files("${rootDir}/detekt.yml"))
	source.setFrom(files("src/main/java", "src/main/kotlin"))
	buildUponDefaultConfig = true
}

android {
	namespace = "com.offsetnull.bt"
	compileSdk = libs.versions.compileSdk.get().toInteger()

	defaultConfig {
		minSdk = libs.versions.minSdk.get().toInteger()
		targetSdk = libs.versions.targetSdk.get().toInteger()
		versionCode = 219
		versionName = "2.0"
	}

	compileOptions {
		sourceCompatibility = JavaVersion.VERSION_17
		targetCompatibility = JavaVersion.VERSION_17
	}

	buildFeatures {
		viewBinding = true
		compose = true
	}

	lint {
		warningsAsErrors = true
		abortOnError = true
		xmlReport = true
		htmlReport = true
		baseline = file("lint-baseline.xml")
	}

	testOptions {
		unitTests.all {
			useJUnitPlatform()
		}
	}

}

dependencies {
	api libs.appcompat
	api libs.material
	api libs.core

	api platform(libs.compose.bom)
	api libs.compose.ui
	api libs.compose.material3
	api libs.compose.ui.tooling.preview
	api libs.activity.compose
	debugImplementation libs.compose.ui.tooling

	api libs.lifecycle.runtime
	api libs.lifecycle.viewmodel
	api libs.lifecycle.viewmodel.compose

	api libs.room.runtime
	api libs.room.ktx
	ksp libs.room.compiler

	api libs.coroutines.core
	api libs.coroutines.android

	api libs.datastore.preferences

	api 'com.github.ncmud.mth:mth-core:1.51'

	testImplementation libs.junit5.api
	testRuntimeOnly libs.junit5.engine
	testRuntimeOnly libs.junit5.launcher
	testImplementation libs.coroutines.test
}
