plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.detekt)
}

detekt {
	config.setFrom(files("${rootDir}/detekt.yml"))
	source.setFrom(files("src"))
	buildUponDefaultConfig = true
}

android {
	namespace "com.offsetnull.bt"
	compileSdk libs.versions.compileSdk.get().toInteger()


	defaultConfig {
		minSdk libs.versions.minSdk.get().toInteger()
		targetSdk libs.versions.targetSdk.get().toInteger()
		versionCode 219
		versionName "2.0"
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}

	kotlinOptions {
		jvmTarget = libs.versions.jvmTarget.get()
	}

	buildFeatures {
		viewBinding true
		compose true
	}

	lint {
		warningsAsErrors false
		abortOnError false
		xmlReport true
		htmlReport true
		baseline file("lint-baseline.xml")
	}

	sourceSets {
		main {
			manifest.srcFile 'AndroidManifest.xml'
			java.srcDirs = ['src']
			resources.srcDirs = ['src']
			res.srcDirs = ['res']
			assets.srcDirs = ['assets']
			jniLibs.srcDirs = ['libs']
		}
	}
}

dependencies {
	api libs.appcompat
	api libs.material
	api libs.core

	api platform(libs.compose.bom)
	api libs.compose.ui
	api libs.compose.material3
	api libs.compose.ui.tooling.preview
	api libs.activity.compose
	debugImplementation libs.compose.ui.tooling
}
