plugins {
    alias(libs.plugins.android.application)
}

android {
	namespace = "org.ncmud.mudwammer.app"
	compileSdk = libs.versions.compileSdk.get().toInteger()

	signingConfigs {
		release {
			storeFile = file("../lib/key/bt_privatekey.keystore")
			storePassword = System.getenv("BT_RELEASE_PASS")
			keyAlias = "btkey"
			keyPassword = System.getenv("BT_RELEASE_PASS")
		}
	}

	defaultConfig {
		minSdk = libs.versions.minSdk.get().toInteger()
		targetSdk = libs.versions.targetSdk.get().toInteger()
		versionCode = 224
		versionName = "2.2"
	}

	compileOptions {
		sourceCompatibility = JavaVersion.VERSION_17
		targetCompatibility = JavaVersion.VERSION_17
	}

	buildTypes {
		release {
			minifyEnabled = true
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
			signingConfig = signingConfigs.release
		}
		debug {
			debuggable = true
		}
	}

	lint {
		warningsAsErrors = true
		abortOnError = true
		xmlReport = true
		htmlReport = true
		baseline = file("lint-baseline.xml")
	}

}

dependencies {
	implementation project(":lib")
}
